exclude: '.tox/|.egg'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        stages: [commit]
