# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.7

env:
  - GH_TOKEN=cb13003e5e786746bddbec4f6dc1f247af5ecaa4

install:
  - pip install tox-travis

script:
  - tox

after_success:
- git config --global user.name "Simonbelete"
- git config --global user.email "simonbelete@gmail.com"
- pip install python-semantic-release
- semantic-release publish
