# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.7

env:
  - GH_TOKEN=c1877cb71e32b1f67ff8025fdcdabd288752ed92

install:
  #- pip install tox-travis
  - pip install -r requirements-dev.txt

script:
  - pytest

after_success:
  - git config --global user.name "Simonbelete"
  - git config --global user.email "simonbelete@gmail.com"
  - semantic-release publish
