########################################################
# Development build                                    #
########################################################
FROM guyaltd/python:mongo AS development

# Workdir
ENV WORK_DIR /usr/src/app
WORKDIR ${WORK_DIR}

COPY . .

CMD flask run